# Generated by Django 5.2.1 on 2025-06-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='todo_type',
        ),
    ]
